name: salon_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_svg:
  firebase_core:
  firebase_database:
  firebase_auth:
  provider:
  intl:
  hive:
  hive_flutter:
  path_provider:
  dropdown_button2:


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/icons/bold/
    - lib/assets/icons/light/
    - lib/assets/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Inter
      fonts:
        - asset: lib/assets/fonts/Inter/static/Inter-Black.ttf
          weight: 900
        - asset: lib/assets/fonts/Inter/static/Inter-ExtraBold.ttf
          weight: 800
        - asset: lib/assets/fonts/Inter/static/Inter-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/Inter/static/Inter-SemiBold.ttf
          weight: 600
        - asset: lib/assets/fonts/Inter/static/Inter-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/Inter/static/Inter-Regular.ttf
          weight: 400
        - asset: lib/assets/fonts/Inter/static/Inter-Light.ttf
          weight: 300
        - asset: lib/assets/fonts/Inter/static/Inter-ExtraLight.ttf
          weight: 200
    - family: Open_Sans
      fonts:
        - asset: lib/assets/fonts/Open_Sans/static/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: lib/assets/fonts/Open_Sans/static/OpenSans-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/Open_Sans/static/OpenSans-SemiBold.ttf
          weight: 600
        - asset: lib/assets/fonts/Open_Sans/static/OpenSans-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/Open_Sans/static/OpenSans-Regular.ttf
          weight: 400
        - asset: lib/assets/fonts/Open_Sans/static/OpenSans-Light.ttf
          weight: 300

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
